---
title: "unit-7-class"
author: "elliothershberg"
date: "2022-05-11"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r library}
library(tidyverse)
library(readxl)
```

```{r data}
df <- read_excel("data/Unit7Data.xlsx")
```

1.

```{r}
# 1 = fracture
sum(df$fracture == 1)

# 0 = not
sum(df$fracture == 0)
```

2.

```{r}
sum(df$lowbmd == 1)
```

3.

Yes

4.

```{r}
df %>%
  filter(fracture == 1) %>%
  summarise(mean = mean(bmdzscore), sd = sd(bmdzscore))
```

```{r}
df %>%
  filter(fracture == 0) %>%
  summarise(mean = mean(bmdzscore), sd = sd(bmdzscore))
```

5.

```{r}
df$fracture_fac <- as.factor(df$fracture)
ggplot(df, aes(x = fracture_fac, y = bmdzscore)) +
  geom_boxplot()
```

6.

A t-test.

7.

Seem normal, variances are similar.

8.

```{r}
t.test(bmdzscore ~ fracture, data = df, var.equal = TRUE)
```

9.

```{r}
percent_table <- df %>%
  group_by(fracture_fac) %>%
  summarise(percent = n()) %>%
  mutate(percent = percent / sum(percent) * 100)

percent_table
```

10.

Chi-square test.

11.

Sparsity.

12.

```{r}
chisq.test(percent_table$percent)
```

